---
- name: Install Java 17 and deploy JAR file
  hosts: all
  become: true
  vars:
    datadog_api_key: "KEY_HERE"
    datadog_apm_instrumentation_enabled: host
    datadog_apm_instrumentation_libraries: ["java:1.38.0"]
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
        
    - name: Create application directory
      file:
        path: /opt/app
        state: directory

    - name: Copy JAR file to /opt/app
      copy:
        src: ./application.jar
        dest: /opt/app/application.jar
        mode: '0755'

    - name: Install Java 17 using dnf
      dnf:
        name: java-17-openjdk
        state: present

    - name: Set Java 17 as the default
      shell: alternatives --set java /usr/lib/jvm/java-17-openjdk-17.0.13.0.11-3.el8.x86_64/bin/java
      changed_when: false

    - name: Execute the JAR file in background
      command: nohup java -jar /opt/app/application.jar > /dev/null 2>&1 &
      async: 1  # Run asynchronously to start the process but not wait for it to complete
      poll: 0    # Do not check the status again after starting the process
