---
- name: Install Java 17 and deploy JAR file
  roles:
    - { role: datadog.datadog, become: yes }
  hosts: all
  become: true
  vars:
    datadog_api_key: "addabd2ca0b314cf9f4c66f5090d8756"
    datadog_apm_instrumentation_enabled: host
    datadog_apm_instrumentation_libraries: ["java:1.38.0"]
  tasks:
    - name: Create application directory
      file:
        path: /opt/app
        state: directory
      when: not (ansible_os_family == 'RedHat')

    - name: Copy JAR file to /opt/app
      copy:
        src: ./application.jar
        dest: /opt/app/application.jar
        mode: '0755'

    - name: Install Java 17 using dnf
      dnf:
        name: java-17-openjdk
        state: present

    - name: Set Java 17 as the default
      shell: alternatives --set java /usr/lib/jvm/java-17-openjdk-17.0.13.0.11-3.el8.x86_64/bin/java
      changed_when: false

    - name: Execute the JAR file in background
      command: nohup java -jar /opt/app/application.jar > /dev/null 2>&1 &
      async: 1  # Run asynchronously to start the process but not wait for it to complete
      poll: 0    # Do not check the status again after starting the process

    - name: Increase open file descriptors for Java
      sysctl:
        name: fs.file-max
        value: 65536
        state: present
      when: ansible_os_family == 'RedHat'
